### ISSUE TITLE
Why wasn't you publish new version on rubygems.org?

### ISSUE THREAD

**Issue by yuri-zubov** [kenn/jquery-rails-cdn#23]
Hello Kenn.

I saw that you update 'jquery-rails-cdn' to new version '1.1.0', but I cann't download this from https://rubygems.org/gems/jquery-rails-cdn. Did you forget publish to rubygems.org??

Thank you

**Comment by kenn** [comment]
Ah, thanks for pointing that out. Just pushed. :)
