### ISSUE TITLE
Major version not honored for local jQuery versions

### ISSUE THREAD

**Issue by yabawock** [kenn/jquery-rails-cdn#24]
The local version of jQuery is currently hardcoded to v1 due to using :jquery as symbol. Setting `Jquery::Rails::Cdn.major_version = 2` doesn't change the behaviour and leads to between the version loaded from CDN in production mode and the jQuery version used during development, test or while being offline.

**Comment by kenn** [comment]
Good catch - Just released as 1.1.1. Thanks for your report! :dancer:
