### ISSUE TITLE
Rails 3 (3.2.12) production: uninitialized constant Jquery::Rails::JQUERY_2_VERSION

### ISSUE THREAD

**Issue by Roko131** [kenn/jquery-rails-cdn#25]
Hello, (first issue I do- be gentle)
In version 1.1.0 you added the use of constant Jquery::Rails::JQUERY_2_VERSION in lib/jquery-rails-cdn.rb

But I believe it's only added by rails4 in the jquery-rails gem- http://www.rubydoc.info/gems/jquery-rails/4.0.5/Jquery/Rails
I use jquery-rails-3.1.4 (I still use rails 3), which doesn't have that constant defined- and since jquery-rails-4.0.5 (or higher) isn't a dependency of jquery-rails-cdn- It just doesn't have it- and eventually the production environment fail bcz this constant isn't defined.

My solution was to use jquery-rails-cdn version 1.0.3 where the Jquery::Rails::JQUERY_2_VERSION isn't used there. (it was added in jquery-rails-cdn version 1.1.0)

Hope I made myself clear.
Have a nice day.

**Comment by hananamar** [comment]
+1 (with Rails 3.2.12)

**Comment by betesh** [comment]
+1 (rails 4.1.12, jquery-rails 3.1.4)
