### ISSUE TITLE
Use jQuery major version 3

### ISSUE THREAD

**Issue by josh08h** [kenn/jquery-rails-cdn#30]
Has any work been planned to allow the use of jQuery@3.x?

**Comment by kenn** [comment]
Nope. PR welcomed 😉

**Comment by kenn** [comment]
I totally forgot, but here https://github.com/kenn/jquery-rails-cdn/pull/27#issuecomment-199635219

> Ah, it hasn't been merged in the upstream yet? I'm going to have to revert until it's accepted then...

Let's check the status of upstream (jquery-rails) first.

**Comment by kenn** [comment]
https://github.com/kenn/jquery-rails-cdn/pull/32

**Comment by kenn** [comment]
Released jquery-rails-cdn-1.2.0
